  - name: "Update apt package index"
    apt:
      update_cache: yes
    become: true

  - name: "Install required packages for docker"
    apt:
      name:
        - openjdk-17-jdk
        - wget
        - curl
        - apt-transport-https
        - ca-certificates
        - vim
        - software-properties-common
        - unzip
      state: present
    become: true

  - name: "Download containerd.io package for ARM64"
    get_url:
      url: https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/arm64/containerd.io_1.6.21-1_arm64.deb
      dest: /tmp/containerd.io_1.6.21-1_arm64.deb
    become: true

  - name: "Install containerd.io"
    apt:
      deb: /tmp/containerd.io_1.6.21-1_arm64.deb
    become: true

  - name: "Docker GPG key"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: true

  - name: "Add Docker repository"
    apt_repository:
      repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu bionic stable"
      state: present
      update_cache: yes
    become: true

  - name: Install docker and dependencies"
    apt:
      name:
        - docker-ce
        - docker-ce-cli
      state: latest
      update_cache: true
    become: true
  
  - name: "Add User at docker group"
    user:
      name: "{{ ansible_user }}"
      groups: "docker"
      append: true
    become: true
